An example of creating a custom transport to implement rate-limiting logic on the client (#2986)
# Summary

This PR introduces an example of a simple wrapper around a transport that prevents that transport from making more than _n_ requests per second. This demonstrates how transports can be composed to add new functionality.

# Test Plan

```
cd examples/rpc-transport-throttled/
pnpm start

> @solana/example-rpc-transport-throttled@ start /home/sol/src/solana-web3.js-git/examples/rpc-transport-throttled
> start-server-and-test '../../scripts/start-shared-test-validator.sh' http://127.0.0.1:8899/health run:example

1: starting server using command "../../scripts/start-shared-test-validator.sh"
and when url "[ 'http://127.0.0.1:8899/health' ]" is responding with HTTP status code 200
running tests using command "npm run run:example"

Started test validator (PID 20904)

> run:example
> tsx src/example.ts

[01:13:08.597] DEBUG (Throttling transport): [transport] Processing request queue
    numQueuedRequests: 1
[01:13:08.600] DEBUG (Throttling transport): [transport] Processing request 1
    requestBudgetRemaining: 2
[01:13:08.600] DEBUG (Throttling transport): [transport] Starting request 1
[01:13:08.617] DEBUG (Throttling transport): [transport] Setting request budget reset deadline for 1 second from now
[01:13:08.618] DEBUG (Throttling transport): [transport] Processing request queue
    numQueuedRequests: 1
[01:13:08.618] DEBUG (Throttling transport): [transport] Processing request 2
    requestBudgetRemaining: 1
[01:13:08.619] DEBUG (Throttling transport): [transport] Starting request 2
[01:13:08.733] INFO (Throttling transport): Request 1 succeeded
    blockhash: "6s8eZiYLsH1mUVDa17MqAK3CbMRAo46PbpAPDWiD5TwU"
    lastValidBlockHeight: 258867382
[01:13:08.734] INFO (Throttling transport): Request 2 succeeded
    blockhash: "6s8eZiYLsH1mUVDa17MqAK3CbMRAo46PbpAPDWiD5TwU"
    lastValidBlockHeight: 258867382
[01:13:09.619] DEBUG (Throttling transport): [transport] Replenishing request budget
[01:13:09.619] DEBUG (Throttling transport): [transport] Processing request queue
    numQueuedRequests: 9
[01:13:09.620] DEBUG (Throttling transport): [transport] Processing request 3
    requestBudgetRemaining: 2
[01:13:09.620] DEBUG (Throttling transport): [transport] Starting request 3
[01:13:09.621] DEBUG (Throttling transport): [transport] Setting request budget reset deadline for 1 second from now
[01:13:09.621] DEBUG (Throttling transport): [transport] Processing request 4
    requestBudgetRemaining: 1
[01:13:09.621] DEBUG (Throttling transport): [transport] Starting request 4
[01:13:09.648] INFO (Throttling transport): Request 3 succeeded
    blockhash: "A2GCudcFMx9B4MPiosArAEwzoybFEHfrzTxc2LdcqENv"
    lastValidBlockHeight: 258867383
[01:13:09.649] INFO (Throttling transport): Request 4 succeeded
    blockhash: "A2GCudcFMx9B4MPiosArAEwzoybFEHfrzTxc2LdcqENv"
    lastValidBlockHeight: 258867383
[01:13:10.621] DEBUG (Throttling transport): [transport] Replenishing request budget
[01:13:10.621] DEBUG (Throttling transport): [transport] Processing request queue
    numQueuedRequests: 7
[01:13:10.621] DEBUG (Throttling transport): [transport] Processing request 5
    requestBudgetRemaining: 2
[01:13:10.621] DEBUG (Throttling transport): [transport] Starting request 5
[01:13:10.622] DEBUG (Throttling transport): [transport] Setting request budget reset deadline for 1 second from now
[01:13:10.622] DEBUG (Throttling transport): [transport] Processing request 6
    requestBudgetRemaining: 1
[01:13:10.622] DEBUG (Throttling transport): [transport] Starting request 6
[01:13:10.649] INFO (Throttling transport): Request 5 succeeded
    blockhash: "FUU9WUbp27KqtFZNxR898iez4kwEMRvFbdu5e12YkwT6"
    lastValidBlockHeight: 258867385
[01:13:10.649] INFO (Throttling transport): Request 6 succeeded
    blockhash: "FUU9WUbp27KqtFZNxR898iez4kwEMRvFbdu5e12YkwT6"
    lastValidBlockHeight: 258867385
[01:13:11.118] DEBUG (Throttling transport): Aborting request 8
[01:13:11.119] ERROR (Throttling transport): Request 8 failed
    error: "Request 8 was aborted"
[01:13:11.623] DEBUG (Throttling transport): [transport] Replenishing request budget
[01:13:11.623] DEBUG (Throttling transport): [transport] Processing request queue
    numQueuedRequests: 5
[01:13:11.623] DEBUG (Throttling transport): [transport] Processing request 7
    requestBudgetRemaining: 2
[01:13:11.623] DEBUG (Throttling transport): [transport] Starting request 7
[01:13:11.624] DEBUG (Throttling transport): [transport] Setting request budget reset deadline for 1 second from now
[01:13:11.624] DEBUG (Throttling transport): [transport] Processing request 8
    requestBudgetRemaining: 1
[01:13:11.624] DEBUG (Throttling transport): [transport] Skipping aborted request 8
[01:13:11.624] DEBUG (Throttling transport): [transport] Processing request 9
    requestBudgetRemaining: 1
[01:13:11.624] DEBUG (Throttling transport): [transport] Starting request 9
[01:13:11.647] INFO (Throttling transport): Request 7 succeeded
    blockhash: "BZg3oyy6nG9X8evP5RNHzTCdkNj547sVnyyUNiQyiQda"
    lastValidBlockHeight: 258867386
[01:13:11.647] INFO (Throttling transport): Request 9 succeeded
    blockhash: "BZg3oyy6nG9X8evP5RNHzTCdkNj547sVnyyUNiQyiQda"
    lastValidBlockHeight: 258867386
[01:13:12.624] DEBUG (Throttling transport): [transport] Replenishing request budget
[01:13:12.624] DEBUG (Throttling transport): [transport] Processing request queue
    numQueuedRequests: 2
[01:13:12.624] DEBUG (Throttling transport): [transport] Processing request 10
    requestBudgetRemaining: 2
[01:13:12.624] DEBUG (Throttling transport): [transport] Starting request 10
[01:13:12.625] DEBUG (Throttling transport): [transport] Setting request budget reset deadline for 1 second from now
[01:13:12.625] DEBUG (Throttling transport): [transport] Processing request 11
    requestBudgetRemaining: 1
[01:13:12.625] DEBUG (Throttling transport): [transport] Starting request 11
[01:13:12.648] INFO (Throttling transport): Request 10 succeeded
    blockhash: "721Vk9ngFto9wyu2e7ZtSMy9fhAhXryJQmnmSGaShzui"
    lastValidBlockHeight: 258867390
[01:13:12.648] INFO (Throttling transport): Request 11 succeeded
    blockhash: "721Vk9ngFto9wyu2e7ZtSMy9fhAhXryJQmnmSGaShzui"
    lastValidBlockHeight: 258867390
[01:13:13.626] DEBUG (Throttling transport): [transport] Replenishing request budget
[01:13:13.626] DEBUG (Throttling transport): [transport] Processing request queue
    numQueuedRequests: 0
```